### ISSUE TITLE
pre-process.py file is missing in the repo

### ISSUE THREAD

**Issue by vikaskesamreddy** [salesforce/DNNC-few-shot-intent#5]
preprocess.py which is mentioned in get_data.sh is missing.

**Comment by vikaskesamreddy** [comment]
this line "python3 preprocess.py" is failing while executing get_data.sh

**Comment by jianguoz** [comment]
> preprocess.py which is mentioned in get_data.sh is missing.

Hi, the file is not missing and it is under the every data folder. Please ref to #2.
